### ISSUE TITLE
Coffee-rails won't work with Dreamhost Rails, version 3.0.3

### ISSUE THREAD

**Issue by noAlvaro** [paulsutcliffe/dreamhostrails#1]
Hi Paul, thanks for sharing.

By the way, your template's Gemfile is absent the `coffee-rails` gem.
Trying to add this, will throw us the following bundler error:

```
Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    coffee-rails (>= 0) ruby depends on
      railties (~> 3.1.0.rc1) ruby
```

... `coffee-rails` lesser stable branch seems to be for Rails 3.1.

_How do you managed to get it working?_

**Comment by paulsutcliffe** [comment]
Hello noAlvaro, the Barista gem compiles the coffsescript, take a look https://github.com/Sutto/barista

**Comment by noAlvaro** [comment]
Thanks Paul, you're right.
