### ISSUE TITLE
MySQL error - socket '/tmp/myqsl.sock'

### ISSUE THREAD

**Issue by dsandstrom** [paulsutcliffe/dreamhostrails#3]
While using rake, I received the error: `Mysql2::Error (Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)`.  I commented `socket: /tmp/mysql.sock` in _database.yml_ and was able to use rake.  I'm not sure if it is a problem on my end or what.

**Comment by dsandstrom** [comment]
I saw this in one of their wiki pages:

```
By default your database.yml often comes generated with a socket connector. Don't use socket for Dreamhost.

Replace/comment out the socket:

#socket: /var/run/mysqld/mysqld.sock 
```

http://wiki.dreamhost.com/Capistrano

**Comment by paulsutcliffe** [comment]
Thanks for your time @dsandstrom, well, for local mysql databases, using the mysql.sock is the way it works, in production servers you shouldn't use the socket, on my recipe the database.yml already lacks from the socket in the production settings, so, unless you are trying to use your production database locally, everything should be fine.

**Comment by dsandstrom** [comment]
Thank you for responding and the template.  It occurs when I create a new project.  So I'm not sure what is happening.  I'm using linux if it makes a difference.  Also, I don't see a _mysql.sock_ file in `/tmp` or on my system.

**Comment by paulsutcliffe** [comment]
I see, in linux is other story, that is a known bug. After you successfully installed mysql-server you need to install some extra packages. Depending on your distro this could be different, for ubuntu or debian for example, you need to install libmysqlclient-dev libmysql-ruby.

```
$ sudo apt-get libmysqlclient-dev libmysql-ruby
```

**Comment by dsandstrom** [comment]
I installed those, but did not seem to change anything.  However, I haven't run across a problem.  Migrations seem to be working fine locally.  

Side note: After spending at least a week (6 months ago) trying to get a app to work on a shared server, I tried again today.  And with your template and lots of googling, I finally got an app to work.  Thanks for doing the leg work and adding this.  However, I will definitely use another host or VPS in the future.  It makes me appreciate heroku so much more, though.

**Comment by dsandstrom** [comment]
I created a new project without this template and it used 

```
socket: /var/run/mysqld/mysqld.sock
```

Of course, I removed the setting from the production settings.  But, it works fine with this different socket.  Not sure if this is Linux specific.
